database:
    image: mysql:latest
    volumes:
        - "./.data/db:/var/lib/mysql"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=via321098via
        - MYSQL_DATABASE=lotufy
        
#version: '3.1'

#services:
#  db:
#      image: postgres:alpine
#      restart: always
#      ports:
#        - 5432:5432
#      environment:
#        POSTGRES_USER: postgres
#        POSTGRES_PASSWORD: P@ssWordLocal

